// See https://aka.ms/new-console-template for more information

var c = new MyClass();
System.Console.WriteLine(c.Prop999);
for (int i = 0; i < 1000; i++)
{
    //Console.WriteLine($"\tpublic virtual int Prop{i} {{ get; set; }}");
}

class MyClass
{
	public virtual int Prop0 { get; set; }
	public virtual int Prop1 { get; set; }
	public virtual int Prop2 { get; set; }
	public virtual int Prop3 { get; set; }
	public virtual int Prop4 { get; set; }
	public virtual int Prop5 { get; set; }
	public virtual int Prop6 { get; set; }
	public virtual int Prop7 { get; set; }
	public virtual int Prop8 { get; set; }
	public virtual int Prop9 { get; set; }
	public virtual int Prop10 { get; set; }
	public virtual int Prop11 { get; set; }
	public virtual int Prop12 { get; set; }
	public virtual int Prop13 { get; set; }
	public virtual int Prop14 { get; set; }
	public virtual int Prop15 { get; set; }
	public virtual int Prop16 { get; set; }
	public virtual int Prop17 { get; set; }
	public virtual int Prop18 { get; set; }
	public virtual int Prop19 { get; set; }
	public virtual int Prop20 { get; set; }
	public virtual int Prop21 { get; set; }
	public virtual int Prop22 { get; set; }
	public virtual int Prop23 { get; set; }
	public virtual int Prop24 { get; set; }
	public virtual int Prop25 { get; set; }
	public virtual int Prop26 { get; set; }
	public virtual int Prop27 { get; set; }
	public virtual int Prop28 { get; set; }
	public virtual int Prop29 { get; set; }
	public virtual int Prop30 { get; set; }
	public virtual int Prop31 { get; set; }
	public virtual int Prop32 { get; set; }
	public virtual int Prop33 { get; set; }
	public virtual int Prop34 { get; set; }
	public virtual int Prop35 { get; set; }
	public virtual int Prop36 { get; set; }
	public virtual int Prop37 { get; set; }
	public virtual int Prop38 { get; set; }
	public virtual int Prop39 { get; set; }
	public virtual int Prop40 { get; set; }
	public virtual int Prop41 { get; set; }
	public virtual int Prop42 { get; set; }
	public virtual int Prop43 { get; set; }
	public virtual int Prop44 { get; set; }
	public virtual int Prop45 { get; set; }
	public virtual int Prop46 { get; set; }
	public virtual int Prop47 { get; set; }
	public virtual int Prop48 { get; set; }
	public virtual int Prop49 { get; set; }
	public virtual int Prop50 { get; set; }
	public virtual int Prop51 { get; set; }
	public virtual int Prop52 { get; set; }
	public virtual int Prop53 { get; set; }
	public virtual int Prop54 { get; set; }
	public virtual int Prop55 { get; set; }
	public virtual int Prop56 { get; set; }
	public virtual int Prop57 { get; set; }
	public virtual int Prop58 { get; set; }
	public virtual int Prop59 { get; set; }
	public virtual int Prop60 { get; set; }
	public virtual int Prop61 { get; set; }
	public virtual int Prop62 { get; set; }
	public virtual int Prop63 { get; set; }
	public virtual int Prop64 { get; set; }
	public virtual int Prop65 { get; set; }
	public virtual int Prop66 { get; set; }
	public virtual int Prop67 { get; set; }
	public virtual int Prop68 { get; set; }
	public virtual int Prop69 { get; set; }
	public virtual int Prop70 { get; set; }
	public virtual int Prop71 { get; set; }
	public virtual int Prop72 { get; set; }
	public virtual int Prop73 { get; set; }
	public virtual int Prop74 { get; set; }
	public virtual int Prop75 { get; set; }
	public virtual int Prop76 { get; set; }
	public virtual int Prop77 { get; set; }
	public virtual int Prop78 { get; set; }
	public virtual int Prop79 { get; set; }
	public virtual int Prop80 { get; set; }
	public virtual int Prop81 { get; set; }
	public virtual int Prop82 { get; set; }
	public virtual int Prop83 { get; set; }
	public virtual int Prop84 { get; set; }
	public virtual int Prop85 { get; set; }
	public virtual int Prop86 { get; set; }
	public virtual int Prop87 { get; set; }
	public virtual int Prop88 { get; set; }
	public virtual int Prop89 { get; set; }
	public virtual int Prop90 { get; set; }
	public virtual int Prop91 { get; set; }
	public virtual int Prop92 { get; set; }
	public virtual int Prop93 { get; set; }
	public virtual int Prop94 { get; set; }
	public virtual int Prop95 { get; set; }
	public virtual int Prop96 { get; set; }
	public virtual int Prop97 { get; set; }
	public virtual int Prop98 { get; set; }
	public virtual int Prop99 { get; set; }
	public virtual int Prop100 { get; set; }
	public virtual int Prop101 { get; set; }
	public virtual int Prop102 { get; set; }
	public virtual int Prop103 { get; set; }
	public virtual int Prop104 { get; set; }
	public virtual int Prop105 { get; set; }
	public virtual int Prop106 { get; set; }
	public virtual int Prop107 { get; set; }
	public virtual int Prop108 { get; set; }
	public virtual int Prop109 { get; set; }
	public virtual int Prop110 { get; set; }
	public virtual int Prop111 { get; set; }
	public virtual int Prop112 { get; set; }
	public virtual int Prop113 { get; set; }
	public virtual int Prop114 { get; set; }
	public virtual int Prop115 { get; set; }
	public virtual int Prop116 { get; set; }
	public virtual int Prop117 { get; set; }
	public virtual int Prop118 { get; set; }
	public virtual int Prop119 { get; set; }
	public virtual int Prop120 { get; set; }
	public virtual int Prop121 { get; set; }
	public virtual int Prop122 { get; set; }
	public virtual int Prop123 { get; set; }
	public virtual int Prop124 { get; set; }
	public virtual int Prop125 { get; set; }
	public virtual int Prop126 { get; set; }
	public virtual int Prop127 { get; set; }
	public virtual int Prop128 { get; set; }
	public virtual int Prop129 { get; set; }
	public virtual int Prop130 { get; set; }
	public virtual int Prop131 { get; set; }
	public virtual int Prop132 { get; set; }
	public virtual int Prop133 { get; set; }
	public virtual int Prop134 { get; set; }
	public virtual int Prop135 { get; set; }
	public virtual int Prop136 { get; set; }
	public virtual int Prop137 { get; set; }
	public virtual int Prop138 { get; set; }
	public virtual int Prop139 { get; set; }
	public virtual int Prop140 { get; set; }
	public virtual int Prop141 { get; set; }
	public virtual int Prop142 { get; set; }
	public virtual int Prop143 { get; set; }
	public virtual int Prop144 { get; set; }
	public virtual int Prop145 { get; set; }
	public virtual int Prop146 { get; set; }
	public virtual int Prop147 { get; set; }
	public virtual int Prop148 { get; set; }
	public virtual int Prop149 { get; set; }
	public virtual int Prop150 { get; set; }
	public virtual int Prop151 { get; set; }
	public virtual int Prop152 { get; set; }
	public virtual int Prop153 { get; set; }
	public virtual int Prop154 { get; set; }
	public virtual int Prop155 { get; set; }
	public virtual int Prop156 { get; set; }
	public virtual int Prop157 { get; set; }
	public virtual int Prop158 { get; set; }
	public virtual int Prop159 { get; set; }
	public virtual int Prop160 { get; set; }
	public virtual int Prop161 { get; set; }
	public virtual int Prop162 { get; set; }
	public virtual int Prop163 { get; set; }
	public virtual int Prop164 { get; set; }
	public virtual int Prop165 { get; set; }
	public virtual int Prop166 { get; set; }
	public virtual int Prop167 { get; set; }
	public virtual int Prop168 { get; set; }
	public virtual int Prop169 { get; set; }
	public virtual int Prop170 { get; set; }
	public virtual int Prop171 { get; set; }
	public virtual int Prop172 { get; set; }
	public virtual int Prop173 { get; set; }
	public virtual int Prop174 { get; set; }
	public virtual int Prop175 { get; set; }
	public virtual int Prop176 { get; set; }
	public virtual int Prop177 { get; set; }
	public virtual int Prop178 { get; set; }
	public virtual int Prop179 { get; set; }
	public virtual int Prop180 { get; set; }
	public virtual int Prop181 { get; set; }
	public virtual int Prop182 { get; set; }
	public virtual int Prop183 { get; set; }
	public virtual int Prop184 { get; set; }
	public virtual int Prop185 { get; set; }
	public virtual int Prop186 { get; set; }
	public virtual int Prop187 { get; set; }
	public virtual int Prop188 { get; set; }
	public virtual int Prop189 { get; set; }
	public virtual int Prop190 { get; set; }
	public virtual int Prop191 { get; set; }
	public virtual int Prop192 { get; set; }
	public virtual int Prop193 { get; set; }
	public virtual int Prop194 { get; set; }
	public virtual int Prop195 { get; set; }
	public virtual int Prop196 { get; set; }
	public virtual int Prop197 { get; set; }
	public virtual int Prop198 { get; set; }
	public virtual int Prop199 { get; set; }
	public virtual int Prop200 { get; set; }
	public virtual int Prop201 { get; set; }
	public virtual int Prop202 { get; set; }
	public virtual int Prop203 { get; set; }
	public virtual int Prop204 { get; set; }
	public virtual int Prop205 { get; set; }
	public virtual int Prop206 { get; set; }
	public virtual int Prop207 { get; set; }
	public virtual int Prop208 { get; set; }
	public virtual int Prop209 { get; set; }
	public virtual int Prop210 { get; set; }
	public virtual int Prop211 { get; set; }
	public virtual int Prop212 { get; set; }
	public virtual int Prop213 { get; set; }
	public virtual int Prop214 { get; set; }
	public virtual int Prop215 { get; set; }
	public virtual int Prop216 { get; set; }
	public virtual int Prop217 { get; set; }
	public virtual int Prop218 { get; set; }
	public virtual int Prop219 { get; set; }
	public virtual int Prop220 { get; set; }
	public virtual int Prop221 { get; set; }
	public virtual int Prop222 { get; set; }
	public virtual int Prop223 { get; set; }
	public virtual int Prop224 { get; set; }
	public virtual int Prop225 { get; set; }
	public virtual int Prop226 { get; set; }
	public virtual int Prop227 { get; set; }
	public virtual int Prop228 { get; set; }
	public virtual int Prop229 { get; set; }
	public virtual int Prop230 { get; set; }
	public virtual int Prop231 { get; set; }
	public virtual int Prop232 { get; set; }
	public virtual int Prop233 { get; set; }
	public virtual int Prop234 { get; set; }
	public virtual int Prop235 { get; set; }
	public virtual int Prop236 { get; set; }
	public virtual int Prop237 { get; set; }
	public virtual int Prop238 { get; set; }
	public virtual int Prop239 { get; set; }
	public virtual int Prop240 { get; set; }
	public virtual int Prop241 { get; set; }
	public virtual int Prop242 { get; set; }
	public virtual int Prop243 { get; set; }
	public virtual int Prop244 { get; set; }
	public virtual int Prop245 { get; set; }
	public virtual int Prop246 { get; set; }
	public virtual int Prop247 { get; set; }
	public virtual int Prop248 { get; set; }
	public virtual int Prop249 { get; set; }
	public virtual int Prop250 { get; set; }
	public virtual int Prop251 { get; set; }
	public virtual int Prop252 { get; set; }
	public virtual int Prop253 { get; set; }
	public virtual int Prop254 { get; set; }
	public virtual int Prop255 { get; set; }
	public virtual int Prop256 { get; set; }
	public virtual int Prop257 { get; set; }
	public virtual int Prop258 { get; set; }
	public virtual int Prop259 { get; set; }
	public virtual int Prop260 { get; set; }
	public virtual int Prop261 { get; set; }
	public virtual int Prop262 { get; set; }
	public virtual int Prop263 { get; set; }
	public virtual int Prop264 { get; set; }
	public virtual int Prop265 { get; set; }
	public virtual int Prop266 { get; set; }
	public virtual int Prop267 { get; set; }
	public virtual int Prop268 { get; set; }
	public virtual int Prop269 { get; set; }
	public virtual int Prop270 { get; set; }
	public virtual int Prop271 { get; set; }
	public virtual int Prop272 { get; set; }
	public virtual int Prop273 { get; set; }
	public virtual int Prop274 { get; set; }
	public virtual int Prop275 { get; set; }
	public virtual int Prop276 { get; set; }
	public virtual int Prop277 { get; set; }
	public virtual int Prop278 { get; set; }
	public virtual int Prop279 { get; set; }
	public virtual int Prop280 { get; set; }
	public virtual int Prop281 { get; set; }
	public virtual int Prop282 { get; set; }
	public virtual int Prop283 { get; set; }
	public virtual int Prop284 { get; set; }
	public virtual int Prop285 { get; set; }
	public virtual int Prop286 { get; set; }
	public virtual int Prop287 { get; set; }
	public virtual int Prop288 { get; set; }
	public virtual int Prop289 { get; set; }
	public virtual int Prop290 { get; set; }
	public virtual int Prop291 { get; set; }
	public virtual int Prop292 { get; set; }
	public virtual int Prop293 { get; set; }
	public virtual int Prop294 { get; set; }
	public virtual int Prop295 { get; set; }
	public virtual int Prop296 { get; set; }
	public virtual int Prop297 { get; set; }
	public virtual int Prop298 { get; set; }
	public virtual int Prop299 { get; set; }
	public virtual int Prop300 { get; set; }
	public virtual int Prop301 { get; set; }
	public virtual int Prop302 { get; set; }
	public virtual int Prop303 { get; set; }
	public virtual int Prop304 { get; set; }
	public virtual int Prop305 { get; set; }
	public virtual int Prop306 { get; set; }
	public virtual int Prop307 { get; set; }
	public virtual int Prop308 { get; set; }
	public virtual int Prop309 { get; set; }
	public virtual int Prop310 { get; set; }
	public virtual int Prop311 { get; set; }
	public virtual int Prop312 { get; set; }
	public virtual int Prop313 { get; set; }
	public virtual int Prop314 { get; set; }
	public virtual int Prop315 { get; set; }
	public virtual int Prop316 { get; set; }
	public virtual int Prop317 { get; set; }
	public virtual int Prop318 { get; set; }
	public virtual int Prop319 { get; set; }
	public virtual int Prop320 { get; set; }
	public virtual int Prop321 { get; set; }
	public virtual int Prop322 { get; set; }
	public virtual int Prop323 { get; set; }
	public virtual int Prop324 { get; set; }
	public virtual int Prop325 { get; set; }
	public virtual int Prop326 { get; set; }
	public virtual int Prop327 { get; set; }
	public virtual int Prop328 { get; set; }
	public virtual int Prop329 { get; set; }
	public virtual int Prop330 { get; set; }
	public virtual int Prop331 { get; set; }
	public virtual int Prop332 { get; set; }
	public virtual int Prop333 { get; set; }
	public virtual int Prop334 { get; set; }
	public virtual int Prop335 { get; set; }
	public virtual int Prop336 { get; set; }
	public virtual int Prop337 { get; set; }
	public virtual int Prop338 { get; set; }
	public virtual int Prop339 { get; set; }
	public virtual int Prop340 { get; set; }
	public virtual int Prop341 { get; set; }
	public virtual int Prop342 { get; set; }
	public virtual int Prop343 { get; set; }
	public virtual int Prop344 { get; set; }
	public virtual int Prop345 { get; set; }
	public virtual int Prop346 { get; set; }
	public virtual int Prop347 { get; set; }
	public virtual int Prop348 { get; set; }
	public virtual int Prop349 { get; set; }
	public virtual int Prop350 { get; set; }
	public virtual int Prop351 { get; set; }
	public virtual int Prop352 { get; set; }
	public virtual int Prop353 { get; set; }
	public virtual int Prop354 { get; set; }
	public virtual int Prop355 { get; set; }
	public virtual int Prop356 { get; set; }
	public virtual int Prop357 { get; set; }
	public virtual int Prop358 { get; set; }
	public virtual int Prop359 { get; set; }
	public virtual int Prop360 { get; set; }
	public virtual int Prop361 { get; set; }
	public virtual int Prop362 { get; set; }
	public virtual int Prop363 { get; set; }
	public virtual int Prop364 { get; set; }
	public virtual int Prop365 { get; set; }
	public virtual int Prop366 { get; set; }
	public virtual int Prop367 { get; set; }
	public virtual int Prop368 { get; set; }
	public virtual int Prop369 { get; set; }
	public virtual int Prop370 { get; set; }
	public virtual int Prop371 { get; set; }
	public virtual int Prop372 { get; set; }
	public virtual int Prop373 { get; set; }
	public virtual int Prop374 { get; set; }
	public virtual int Prop375 { get; set; }
	public virtual int Prop376 { get; set; }
	public virtual int Prop377 { get; set; }
	public virtual int Prop378 { get; set; }
	public virtual int Prop379 { get; set; }
	public virtual int Prop380 { get; set; }
	public virtual int Prop381 { get; set; }
	public virtual int Prop382 { get; set; }
	public virtual int Prop383 { get; set; }
	public virtual int Prop384 { get; set; }
	public virtual int Prop385 { get; set; }
	public virtual int Prop386 { get; set; }
	public virtual int Prop387 { get; set; }
	public virtual int Prop388 { get; set; }
	public virtual int Prop389 { get; set; }
	public virtual int Prop390 { get; set; }
	public virtual int Prop391 { get; set; }
	public virtual int Prop392 { get; set; }
	public virtual int Prop393 { get; set; }
	public virtual int Prop394 { get; set; }
	public virtual int Prop395 { get; set; }
	public virtual int Prop396 { get; set; }
	public virtual int Prop397 { get; set; }
	public virtual int Prop398 { get; set; }
	public virtual int Prop399 { get; set; }
	public virtual int Prop400 { get; set; }
	public virtual int Prop401 { get; set; }
	public virtual int Prop402 { get; set; }
	public virtual int Prop403 { get; set; }
	public virtual int Prop404 { get; set; }
	public virtual int Prop405 { get; set; }
	public virtual int Prop406 { get; set; }
	public virtual int Prop407 { get; set; }
	public virtual int Prop408 { get; set; }
	public virtual int Prop409 { get; set; }
	public virtual int Prop410 { get; set; }
	public virtual int Prop411 { get; set; }
	public virtual int Prop412 { get; set; }
	public virtual int Prop413 { get; set; }
	public virtual int Prop414 { get; set; }
	public virtual int Prop415 { get; set; }
	public virtual int Prop416 { get; set; }
	public virtual int Prop417 { get; set; }
	public virtual int Prop418 { get; set; }
	public virtual int Prop419 { get; set; }
	public virtual int Prop420 { get; set; }
	public virtual int Prop421 { get; set; }
	public virtual int Prop422 { get; set; }
	public virtual int Prop423 { get; set; }
	public virtual int Prop424 { get; set; }
	public virtual int Prop425 { get; set; }
	public virtual int Prop426 { get; set; }
	public virtual int Prop427 { get; set; }
	public virtual int Prop428 { get; set; }
	public virtual int Prop429 { get; set; }
	public virtual int Prop430 { get; set; }
	public virtual int Prop431 { get; set; }
	public virtual int Prop432 { get; set; }
	public virtual int Prop433 { get; set; }
	public virtual int Prop434 { get; set; }
	public virtual int Prop435 { get; set; }
	public virtual int Prop436 { get; set; }
	public virtual int Prop437 { get; set; }
	public virtual int Prop438 { get; set; }
	public virtual int Prop439 { get; set; }
	public virtual int Prop440 { get; set; }
	public virtual int Prop441 { get; set; }
	public virtual int Prop442 { get; set; }
	public virtual int Prop443 { get; set; }
	public virtual int Prop444 { get; set; }
	public virtual int Prop445 { get; set; }
	public virtual int Prop446 { get; set; }
	public virtual int Prop447 { get; set; }
	public virtual int Prop448 { get; set; }
	public virtual int Prop449 { get; set; }
	public virtual int Prop450 { get; set; }
	public virtual int Prop451 { get; set; }
	public virtual int Prop452 { get; set; }
	public virtual int Prop453 { get; set; }
	public virtual int Prop454 { get; set; }
	public virtual int Prop455 { get; set; }
	public virtual int Prop456 { get; set; }
	public virtual int Prop457 { get; set; }
	public virtual int Prop458 { get; set; }
	public virtual int Prop459 { get; set; }
	public virtual int Prop460 { get; set; }
	public virtual int Prop461 { get; set; }
	public virtual int Prop462 { get; set; }
	public virtual int Prop463 { get; set; }
	public virtual int Prop464 { get; set; }
	public virtual int Prop465 { get; set; }
	public virtual int Prop466 { get; set; }
	public virtual int Prop467 { get; set; }
	public virtual int Prop468 { get; set; }
	public virtual int Prop469 { get; set; }
	public virtual int Prop470 { get; set; }
	public virtual int Prop471 { get; set; }
	public virtual int Prop472 { get; set; }
	public virtual int Prop473 { get; set; }
	public virtual int Prop474 { get; set; }
	public virtual int Prop475 { get; set; }
	public virtual int Prop476 { get; set; }
	public virtual int Prop477 { get; set; }
	public virtual int Prop478 { get; set; }
	public virtual int Prop479 { get; set; }
	public virtual int Prop480 { get; set; }
	public virtual int Prop481 { get; set; }
	public virtual int Prop482 { get; set; }
	public virtual int Prop483 { get; set; }
	public virtual int Prop484 { get; set; }
	public virtual int Prop485 { get; set; }
	public virtual int Prop486 { get; set; }
	public virtual int Prop487 { get; set; }
	public virtual int Prop488 { get; set; }
	public virtual int Prop489 { get; set; }
	public virtual int Prop490 { get; set; }
	public virtual int Prop491 { get; set; }
	public virtual int Prop492 { get; set; }
	public virtual int Prop493 { get; set; }
	public virtual int Prop494 { get; set; }
	public virtual int Prop495 { get; set; }
	public virtual int Prop496 { get; set; }
	public virtual int Prop497 { get; set; }
	public virtual int Prop498 { get; set; }
	public virtual int Prop499 { get; set; }
	public virtual int Prop500 { get; set; }
	public virtual int Prop501 { get; set; }
	public virtual int Prop502 { get; set; }
	public virtual int Prop503 { get; set; }
	public virtual int Prop504 { get; set; }
	public virtual int Prop505 { get; set; }
	public virtual int Prop506 { get; set; }
	public virtual int Prop507 { get; set; }
	public virtual int Prop508 { get; set; }
	public virtual int Prop509 { get; set; }
	public virtual int Prop510 { get; set; }
	public virtual int Prop511 { get; set; }
	public virtual int Prop512 { get; set; }
	public virtual int Prop513 { get; set; }
	public virtual int Prop514 { get; set; }
	public virtual int Prop515 { get; set; }
	public virtual int Prop516 { get; set; }
	public virtual int Prop517 { get; set; }
	public virtual int Prop518 { get; set; }
	public virtual int Prop519 { get; set; }
	public virtual int Prop520 { get; set; }
	public virtual int Prop521 { get; set; }
	public virtual int Prop522 { get; set; }
	public virtual int Prop523 { get; set; }
	public virtual int Prop524 { get; set; }
	public virtual int Prop525 { get; set; }
	public virtual int Prop526 { get; set; }
	public virtual int Prop527 { get; set; }
	public virtual int Prop528 { get; set; }
	public virtual int Prop529 { get; set; }
	public virtual int Prop530 { get; set; }
	public virtual int Prop531 { get; set; }
	public virtual int Prop532 { get; set; }
	public virtual int Prop533 { get; set; }
	public virtual int Prop534 { get; set; }
	public virtual int Prop535 { get; set; }
	public virtual int Prop536 { get; set; }
	public virtual int Prop537 { get; set; }
	public virtual int Prop538 { get; set; }
	public virtual int Prop539 { get; set; }
	public virtual int Prop540 { get; set; }
	public virtual int Prop541 { get; set; }
	public virtual int Prop542 { get; set; }
	public virtual int Prop543 { get; set; }
	public virtual int Prop544 { get; set; }
	public virtual int Prop545 { get; set; }
	public virtual int Prop546 { get; set; }
	public virtual int Prop547 { get; set; }
	public virtual int Prop548 { get; set; }
	public virtual int Prop549 { get; set; }
	public virtual int Prop550 { get; set; }
	public virtual int Prop551 { get; set; }
	public virtual int Prop552 { get; set; }
	public virtual int Prop553 { get; set; }
	public virtual int Prop554 { get; set; }
	public virtual int Prop555 { get; set; }
	public virtual int Prop556 { get; set; }
	public virtual int Prop557 { get; set; }
	public virtual int Prop558 { get; set; }
	public virtual int Prop559 { get; set; }
	public virtual int Prop560 { get; set; }
	public virtual int Prop561 { get; set; }
	public virtual int Prop562 { get; set; }
	public virtual int Prop563 { get; set; }
	public virtual int Prop564 { get; set; }
	public virtual int Prop565 { get; set; }
	public virtual int Prop566 { get; set; }
	public virtual int Prop567 { get; set; }
	public virtual int Prop568 { get; set; }
	public virtual int Prop569 { get; set; }
	public virtual int Prop570 { get; set; }
	public virtual int Prop571 { get; set; }
	public virtual int Prop572 { get; set; }
	public virtual int Prop573 { get; set; }
	public virtual int Prop574 { get; set; }
	public virtual int Prop575 { get; set; }
	public virtual int Prop576 { get; set; }
	public virtual int Prop577 { get; set; }
	public virtual int Prop578 { get; set; }
	public virtual int Prop579 { get; set; }
	public virtual int Prop580 { get; set; }
	public virtual int Prop581 { get; set; }
	public virtual int Prop582 { get; set; }
	public virtual int Prop583 { get; set; }
	public virtual int Prop584 { get; set; }
	public virtual int Prop585 { get; set; }
	public virtual int Prop586 { get; set; }
	public virtual int Prop587 { get; set; }
	public virtual int Prop588 { get; set; }
	public virtual int Prop589 { get; set; }
	public virtual int Prop590 { get; set; }
	public virtual int Prop591 { get; set; }
	public virtual int Prop592 { get; set; }
	public virtual int Prop593 { get; set; }
	public virtual int Prop594 { get; set; }
	public virtual int Prop595 { get; set; }
	public virtual int Prop596 { get; set; }
	public virtual int Prop597 { get; set; }
	public virtual int Prop598 { get; set; }
	public virtual int Prop599 { get; set; }
	public virtual int Prop600 { get; set; }
	public virtual int Prop601 { get; set; }
	public virtual int Prop602 { get; set; }
	public virtual int Prop603 { get; set; }
	public virtual int Prop604 { get; set; }
	public virtual int Prop605 { get; set; }
	public virtual int Prop606 { get; set; }
	public virtual int Prop607 { get; set; }
	public virtual int Prop608 { get; set; }
	public virtual int Prop609 { get; set; }
	public virtual int Prop610 { get; set; }
	public virtual int Prop611 { get; set; }
	public virtual int Prop612 { get; set; }
	public virtual int Prop613 { get; set; }
	public virtual int Prop614 { get; set; }
	public virtual int Prop615 { get; set; }
	public virtual int Prop616 { get; set; }
	public virtual int Prop617 { get; set; }
	public virtual int Prop618 { get; set; }
	public virtual int Prop619 { get; set; }
	public virtual int Prop620 { get; set; }
	public virtual int Prop621 { get; set; }
	public virtual int Prop622 { get; set; }
	public virtual int Prop623 { get; set; }
	public virtual int Prop624 { get; set; }
	public virtual int Prop625 { get; set; }
	public virtual int Prop626 { get; set; }
	public virtual int Prop627 { get; set; }
	public virtual int Prop628 { get; set; }
	public virtual int Prop629 { get; set; }
	public virtual int Prop630 { get; set; }
	public virtual int Prop631 { get; set; }
	public virtual int Prop632 { get; set; }
	public virtual int Prop633 { get; set; }
	public virtual int Prop634 { get; set; }
	public virtual int Prop635 { get; set; }
	public virtual int Prop636 { get; set; }
	public virtual int Prop637 { get; set; }
	public virtual int Prop638 { get; set; }
	public virtual int Prop639 { get; set; }
	public virtual int Prop640 { get; set; }
	public virtual int Prop641 { get; set; }
	public virtual int Prop642 { get; set; }
	public virtual int Prop643 { get; set; }
	public virtual int Prop644 { get; set; }
	public virtual int Prop645 { get; set; }
	public virtual int Prop646 { get; set; }
	public virtual int Prop647 { get; set; }
	public virtual int Prop648 { get; set; }
	public virtual int Prop649 { get; set; }
	public virtual int Prop650 { get; set; }
	public virtual int Prop651 { get; set; }
	public virtual int Prop652 { get; set; }
	public virtual int Prop653 { get; set; }
	public virtual int Prop654 { get; set; }
	public virtual int Prop655 { get; set; }
	public virtual int Prop656 { get; set; }
	public virtual int Prop657 { get; set; }
	public virtual int Prop658 { get; set; }
	public virtual int Prop659 { get; set; }
	public virtual int Prop660 { get; set; }
	public virtual int Prop661 { get; set; }
	public virtual int Prop662 { get; set; }
	public virtual int Prop663 { get; set; }
	public virtual int Prop664 { get; set; }
	public virtual int Prop665 { get; set; }
	public virtual int Prop666 { get; set; }
	public virtual int Prop667 { get; set; }
	public virtual int Prop668 { get; set; }
	public virtual int Prop669 { get; set; }
	public virtual int Prop670 { get; set; }
	public virtual int Prop671 { get; set; }
	public virtual int Prop672 { get; set; }
	public virtual int Prop673 { get; set; }
	public virtual int Prop674 { get; set; }
	public virtual int Prop675 { get; set; }
	public virtual int Prop676 { get; set; }
	public virtual int Prop677 { get; set; }
	public virtual int Prop678 { get; set; }
	public virtual int Prop679 { get; set; }
	public virtual int Prop680 { get; set; }
	public virtual int Prop681 { get; set; }
	public virtual int Prop682 { get; set; }
	public virtual int Prop683 { get; set; }
	public virtual int Prop684 { get; set; }
	public virtual int Prop685 { get; set; }
	public virtual int Prop686 { get; set; }
	public virtual int Prop687 { get; set; }
	public virtual int Prop688 { get; set; }
	public virtual int Prop689 { get; set; }
	public virtual int Prop690 { get; set; }
	public virtual int Prop691 { get; set; }
	public virtual int Prop692 { get; set; }
	public virtual int Prop693 { get; set; }
	public virtual int Prop694 { get; set; }
	public virtual int Prop695 { get; set; }
	public virtual int Prop696 { get; set; }
	public virtual int Prop697 { get; set; }
	public virtual int Prop698 { get; set; }
	public virtual int Prop699 { get; set; }
	public virtual int Prop700 { get; set; }
	public virtual int Prop701 { get; set; }
	public virtual int Prop702 { get; set; }
	public virtual int Prop703 { get; set; }
	public virtual int Prop704 { get; set; }
	public virtual int Prop705 { get; set; }
	public virtual int Prop706 { get; set; }
	public virtual int Prop707 { get; set; }
	public virtual int Prop708 { get; set; }
	public virtual int Prop709 { get; set; }
	public virtual int Prop710 { get; set; }
	public virtual int Prop711 { get; set; }
	public virtual int Prop712 { get; set; }
	public virtual int Prop713 { get; set; }
	public virtual int Prop714 { get; set; }
	public virtual int Prop715 { get; set; }
	public virtual int Prop716 { get; set; }
	public virtual int Prop717 { get; set; }
	public virtual int Prop718 { get; set; }
	public virtual int Prop719 { get; set; }
	public virtual int Prop720 { get; set; }
	public virtual int Prop721 { get; set; }
	public virtual int Prop722 { get; set; }
	public virtual int Prop723 { get; set; }
	public virtual int Prop724 { get; set; }
	public virtual int Prop725 { get; set; }
	public virtual int Prop726 { get; set; }
	public virtual int Prop727 { get; set; }
	public virtual int Prop728 { get; set; }
	public virtual int Prop729 { get; set; }
	public virtual int Prop730 { get; set; }
	public virtual int Prop731 { get; set; }
	public virtual int Prop732 { get; set; }
	public virtual int Prop733 { get; set; }
	public virtual int Prop734 { get; set; }
	public virtual int Prop735 { get; set; }
	public virtual int Prop736 { get; set; }
	public virtual int Prop737 { get; set; }
	public virtual int Prop738 { get; set; }
	public virtual int Prop739 { get; set; }
	public virtual int Prop740 { get; set; }
	public virtual int Prop741 { get; set; }
	public virtual int Prop742 { get; set; }
	public virtual int Prop743 { get; set; }
	public virtual int Prop744 { get; set; }
	public virtual int Prop745 { get; set; }
	public virtual int Prop746 { get; set; }
	public virtual int Prop747 { get; set; }
	public virtual int Prop748 { get; set; }
	public virtual int Prop749 { get; set; }
	public virtual int Prop750 { get; set; }
	public virtual int Prop751 { get; set; }
	public virtual int Prop752 { get; set; }
	public virtual int Prop753 { get; set; }
	public virtual int Prop754 { get; set; }
	public virtual int Prop755 { get; set; }
	public virtual int Prop756 { get; set; }
	public virtual int Prop757 { get; set; }
	public virtual int Prop758 { get; set; }
	public virtual int Prop759 { get; set; }
	public virtual int Prop760 { get; set; }
	public virtual int Prop761 { get; set; }
	public virtual int Prop762 { get; set; }
	public virtual int Prop763 { get; set; }
	public virtual int Prop764 { get; set; }
	public virtual int Prop765 { get; set; }
	public virtual int Prop766 { get; set; }
	public virtual int Prop767 { get; set; }
	public virtual int Prop768 { get; set; }
	public virtual int Prop769 { get; set; }
	public virtual int Prop770 { get; set; }
	public virtual int Prop771 { get; set; }
	public virtual int Prop772 { get; set; }
	public virtual int Prop773 { get; set; }
	public virtual int Prop774 { get; set; }
	public virtual int Prop775 { get; set; }
	public virtual int Prop776 { get; set; }
	public virtual int Prop777 { get; set; }
	public virtual int Prop778 { get; set; }
	public virtual int Prop779 { get; set; }
	public virtual int Prop780 { get; set; }
	public virtual int Prop781 { get; set; }
	public virtual int Prop782 { get; set; }
	public virtual int Prop783 { get; set; }
	public virtual int Prop784 { get; set; }
	public virtual int Prop785 { get; set; }
	public virtual int Prop786 { get; set; }
	public virtual int Prop787 { get; set; }
	public virtual int Prop788 { get; set; }
	public virtual int Prop789 { get; set; }
	public virtual int Prop790 { get; set; }
	public virtual int Prop791 { get; set; }
	public virtual int Prop792 { get; set; }
	public virtual int Prop793 { get; set; }
	public virtual int Prop794 { get; set; }
	public virtual int Prop795 { get; set; }
	public virtual int Prop796 { get; set; }
	public virtual int Prop797 { get; set; }
	public virtual int Prop798 { get; set; }
	public virtual int Prop799 { get; set; }
	public virtual int Prop800 { get; set; }
	public virtual int Prop801 { get; set; }
	public virtual int Prop802 { get; set; }
	public virtual int Prop803 { get; set; }
	public virtual int Prop804 { get; set; }
	public virtual int Prop805 { get; set; }
	public virtual int Prop806 { get; set; }
	public virtual int Prop807 { get; set; }
	public virtual int Prop808 { get; set; }
	public virtual int Prop809 { get; set; }
	public virtual int Prop810 { get; set; }
	public virtual int Prop811 { get; set; }
	public virtual int Prop812 { get; set; }
	public virtual int Prop813 { get; set; }
	public virtual int Prop814 { get; set; }
	public virtual int Prop815 { get; set; }
	public virtual int Prop816 { get; set; }
	public virtual int Prop817 { get; set; }
	public virtual int Prop818 { get; set; }
	public virtual int Prop819 { get; set; }
	public virtual int Prop820 { get; set; }
	public virtual int Prop821 { get; set; }
	public virtual int Prop822 { get; set; }
	public virtual int Prop823 { get; set; }
	public virtual int Prop824 { get; set; }
	public virtual int Prop825 { get; set; }
	public virtual int Prop826 { get; set; }
	public virtual int Prop827 { get; set; }
	public virtual int Prop828 { get; set; }
	public virtual int Prop829 { get; set; }
	public virtual int Prop830 { get; set; }
	public virtual int Prop831 { get; set; }
	public virtual int Prop832 { get; set; }
	public virtual int Prop833 { get; set; }
	public virtual int Prop834 { get; set; }
	public virtual int Prop835 { get; set; }
	public virtual int Prop836 { get; set; }
	public virtual int Prop837 { get; set; }
	public virtual int Prop838 { get; set; }
	public virtual int Prop839 { get; set; }
	public virtual int Prop840 { get; set; }
	public virtual int Prop841 { get; set; }
	public virtual int Prop842 { get; set; }
	public virtual int Prop843 { get; set; }
	public virtual int Prop844 { get; set; }
	public virtual int Prop845 { get; set; }
	public virtual int Prop846 { get; set; }
	public virtual int Prop847 { get; set; }
	public virtual int Prop848 { get; set; }
	public virtual int Prop849 { get; set; }
	public virtual int Prop850 { get; set; }
	public virtual int Prop851 { get; set; }
	public virtual int Prop852 { get; set; }
	public virtual int Prop853 { get; set; }
	public virtual int Prop854 { get; set; }
	public virtual int Prop855 { get; set; }
	public virtual int Prop856 { get; set; }
	public virtual int Prop857 { get; set; }
	public virtual int Prop858 { get; set; }
	public virtual int Prop859 { get; set; }
	public virtual int Prop860 { get; set; }
	public virtual int Prop861 { get; set; }
	public virtual int Prop862 { get; set; }
	public virtual int Prop863 { get; set; }
	public virtual int Prop864 { get; set; }
	public virtual int Prop865 { get; set; }
	public virtual int Prop866 { get; set; }
	public virtual int Prop867 { get; set; }
	public virtual int Prop868 { get; set; }
	public virtual int Prop869 { get; set; }
	public virtual int Prop870 { get; set; }
	public virtual int Prop871 { get; set; }
	public virtual int Prop872 { get; set; }
	public virtual int Prop873 { get; set; }
	public virtual int Prop874 { get; set; }
	public virtual int Prop875 { get; set; }
	public virtual int Prop876 { get; set; }
	public virtual int Prop877 { get; set; }
	public virtual int Prop878 { get; set; }
	public virtual int Prop879 { get; set; }
	public virtual int Prop880 { get; set; }
	public virtual int Prop881 { get; set; }
	public virtual int Prop882 { get; set; }
	public virtual int Prop883 { get; set; }
	public virtual int Prop884 { get; set; }
	public virtual int Prop885 { get; set; }
	public virtual int Prop886 { get; set; }
	public virtual int Prop887 { get; set; }
	public virtual int Prop888 { get; set; }
	public virtual int Prop889 { get; set; }
	public virtual int Prop890 { get; set; }
	public virtual int Prop891 { get; set; }
	public virtual int Prop892 { get; set; }
	public virtual int Prop893 { get; set; }
	public virtual int Prop894 { get; set; }
	public virtual int Prop895 { get; set; }
	public virtual int Prop896 { get; set; }
	public virtual int Prop897 { get; set; }
	public virtual int Prop898 { get; set; }
	public virtual int Prop899 { get; set; }
	public virtual int Prop900 { get; set; }
	public virtual int Prop901 { get; set; }
	public virtual int Prop902 { get; set; }
	public virtual int Prop903 { get; set; }
	public virtual int Prop904 { get; set; }
	public virtual int Prop905 { get; set; }
	public virtual int Prop906 { get; set; }
	public virtual int Prop907 { get; set; }
	public virtual int Prop908 { get; set; }
	public virtual int Prop909 { get; set; }
	public virtual int Prop910 { get; set; }
	public virtual int Prop911 { get; set; }
	public virtual int Prop912 { get; set; }
	public virtual int Prop913 { get; set; }
	public virtual int Prop914 { get; set; }
	public virtual int Prop915 { get; set; }
	public virtual int Prop916 { get; set; }
	public virtual int Prop917 { get; set; }
	public virtual int Prop918 { get; set; }
	public virtual int Prop919 { get; set; }
	public virtual int Prop920 { get; set; }
	public virtual int Prop921 { get; set; }
	public virtual int Prop922 { get; set; }
	public virtual int Prop923 { get; set; }
	public virtual int Prop924 { get; set; }
	public virtual int Prop925 { get; set; }
	public virtual int Prop926 { get; set; }
	public virtual int Prop927 { get; set; }
	public virtual int Prop928 { get; set; }
	public virtual int Prop929 { get; set; }
	public virtual int Prop930 { get; set; }
	public virtual int Prop931 { get; set; }
	public virtual int Prop932 { get; set; }
	public virtual int Prop933 { get; set; }
	public virtual int Prop934 { get; set; }
	public virtual int Prop935 { get; set; }
	public virtual int Prop936 { get; set; }
	public virtual int Prop937 { get; set; }
	public virtual int Prop938 { get; set; }
	public virtual int Prop939 { get; set; }
	public virtual int Prop940 { get; set; }
	public virtual int Prop941 { get; set; }
	public virtual int Prop942 { get; set; }
	public virtual int Prop943 { get; set; }
	public virtual int Prop944 { get; set; }
	public virtual int Prop945 { get; set; }
	public virtual int Prop946 { get; set; }
	public virtual int Prop947 { get; set; }
	public virtual int Prop948 { get; set; }
	public virtual int Prop949 { get; set; }
	public virtual int Prop950 { get; set; }
	public virtual int Prop951 { get; set; }
	public virtual int Prop952 { get; set; }
	public virtual int Prop953 { get; set; }
	public virtual int Prop954 { get; set; }
	public virtual int Prop955 { get; set; }
	public virtual int Prop956 { get; set; }
	public virtual int Prop957 { get; set; }
	public virtual int Prop958 { get; set; }
	public virtual int Prop959 { get; set; }
	public virtual int Prop960 { get; set; }
	public virtual int Prop961 { get; set; }
	public virtual int Prop962 { get; set; }
	public virtual int Prop963 { get; set; }
	public virtual int Prop964 { get; set; }
	public virtual int Prop965 { get; set; }
	public virtual int Prop966 { get; set; }
	public virtual int Prop967 { get; set; }
	public virtual int Prop968 { get; set; }
	public virtual int Prop969 { get; set; }
	public virtual int Prop970 { get; set; }
	public virtual int Prop971 { get; set; }
	public virtual int Prop972 { get; set; }
	public virtual int Prop973 { get; set; }
	public virtual int Prop974 { get; set; }
	public virtual int Prop975 { get; set; }
	public virtual int Prop976 { get; set; }
	public virtual int Prop977 { get; set; }
	public virtual int Prop978 { get; set; }
	public virtual int Prop979 { get; set; }
	public virtual int Prop980 { get; set; }
	public virtual int Prop981 { get; set; }
	public virtual int Prop982 { get; set; }
	public virtual int Prop983 { get; set; }
	public virtual int Prop984 { get; set; }
	public virtual int Prop985 { get; set; }
	public virtual int Prop986 { get; set; }
	public virtual int Prop987 { get; set; }
	public virtual int Prop988 { get; set; }
	public virtual int Prop989 { get; set; }
	public virtual int Prop990 { get; set; }
	public virtual int Prop991 { get; set; }
	public virtual int Prop992 { get; set; }
	public virtual int Prop993 { get; set; }
	public virtual int Prop994 { get; set; }
	public virtual int Prop995 { get; set; }
	public virtual int Prop996 { get; set; }
	public virtual int Prop997 { get; set; }
	public virtual int Prop998 { get; set; }
	public virtual int Prop999 { get; set; }
}